---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/magento-mcom/go-starter

image_pull_secrets:
  - docker_registry

steps:
- name: install
  image: mcom/gobuilder:1.12
  pull: always
  commands: [ "make dep" ]

- name: test
  image: mcom/gobuilder:1.12
  pull: always
  commands: [ "make test" ]

---
kind: pipeline
name: release

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/magento-mcom/go-starter

image_pull_secrets:
  - docker_registry

depends_on: [ test ]

trigger:
  event: [ tag ]
  status: [ "success"]

steps:
- name: install
  image: mcom/gobuilder:1.12
  pull: always
  commands: [ "make dep" ]

- name: build
  image: mcom/gobuilder:1.12cross
  pull: always
  commands: [ "make build" ]
  environment:
    BUILDCOMMIT: ${DRONE_COMMIT_SHA:0:7}
    BUILDLDFLAGS: -linkmode external -s
    BUILDOUTPREFIX: build/darwin-amd64/
    BUILDTAG: ${DRONE_TAG}
    CC: o64-clang
    CXX: o64-clang++
    GOARCH: amd64
    GOOS: darwin

- name: pack
  image: mcom/gobuilder:1.12
  pull: always
  commands: [ "tar -C build/darwin-amd64 -cvzf go-starter-darwin-amd64.tgz ." ]

- name: release
  image: socialengine/github-release
  pull: always
  commands:
  - github-release release --user magento-mcom --repo go-starter --tag ${DRONE_TAG} --name ${DRONE_TAG}
  - github-release upload  --user magento-mcom --repo go-starter --tag ${DRONE_TAG} --name go-starter-darwin-amd64.tgz --file ./go-starter-darwin-amd64.tgz
  environment:
    GITHUB_RELEASE_VERSION: v0.7.2
    GITHUB_TOKEN: { from_secret: github_token }

- name: update-tap
  pull: always
  image: mcom/brewbuilder
  settings:
    formula: Formula/go-starter.rb
    hash_file: go-starter-darwin-amd64.tgz
    revision: ${DRONE_BUILD_NUMBER}
    tap: https://github.com/magento-mcom/homebrew-tap
    template: formula.template.rb
    url: https://github.com/magento-mcom/go-starter/releases/download/${DRONE_TAG}/go-starter-darwin-amd64.tgz
    version: ${DRONE_TAG}
  environment:
    GITHUB_TOKEN: { from_secret: github_token }

---
kind: secret
name: docker_registry
get:
  path: secret/dx_magento_mom_droneci/registry/docker.io
  name: config

---
kind: secret
name: github_token
get:
  path: secret/dx_magento_mom_droneci/github
  name: token
