---
kind: pipeline
name: test

workspace:
  base: /go
  path: src/github.com/magento-mcom/go-starter

image_pull_secrets:
  - docker_registry

steps:
- name: dep
  image: mcom/gobuilder:1.12
  pull: always
  commands: [ "make dep" ]

- name: test
  image: mcom/gobuilder:1.12
  pull: always
  commands: [ "make test" ]

---
kind: pipeline
name: release

workspace:
  base: /go
  path: src/github.com/magento-mcom/go-starter

image_pull_secrets:
  - docker_registry

depends_on: [ test ]

trigger:
  event: [ tag ]
  status: [ "success"]

steps:
- name: dep
  image: mcom/gobuilder:1.12
  pull: always
  commands: [ "make dep" ]

- name: build linux
  image: mcom/gobuilder:1.12
  pull: always
  commands: [ "make build" ]
  environment:
    BUILDARGS: -a -installsuffix cgo
    BUILDCOMMIT: ${DRONE_COMMIT_SHA:0:7}
    BUILDLDFLAGS: -extldflags "-static"
    BUILDOUTPREFIX: build/linux-amd64/
    BUILDTAG: ${DRONE_TAG}
    GOARCH: amd64
    GOOS: linux

- name: build darwin
  image: mcom/gobuilder:1.12cross
  pull: always
  commands: [ "make build" ]
  environment:
    BUILDCOMMIT: ${DRONE_COMMIT_SHA:0:7}
    BUILDLDFLAGS: -linkmode external -s
    BUILDOUTPREFIX: build/darwin-amd64/
    BUILDTAG: ${DRONE_TAG}
    CC: o64-clang
    CXX: o64-clang++
    GOARCH: amd64
    GOOS: darwin

- name: pack tarball
  image: mcom/zipbuilder
  pull: always
  commands:
    - "tar -C build/darwin-amd64 -cvzf go-starter-darwin-amd64.tgz ."
    - "tar -C build/linux-amd64  -cvzf go-starter-linux-amd64.tgz  ."

- name: docker image
  image: plugins/docker:latest
  settings:
    username: { from_secret: docker_username }
    password: { from_secret: docker_password }
    repo: mcom/gostarter
    tags: [ "${DRONE_TAG=latest}", "${DRONE_COMMIT_SHA:0:7}" ]

- name: github release
  image: socialengine/github-release
  pull: always
  commands:
  - github-release release --user magento-mcom --repo go-starter --tag ${DRONE_TAG} --name ${DRONE_TAG}
  - github-release upload  --user magento-mcom --repo go-starter --tag ${DRONE_TAG} --name go-starter-darwin-amd64.tgz --file ./go-starter-darwin-amd64.tgz
  - github-release upload  --user magento-mcom --repo go-starter --tag ${DRONE_TAG} --name go-starter-linux-amd64.tgz --file ./go-starter-linux-amd64.tgz
  environment:
    GITHUB_RELEASE_VERSION: v0.7.2
    GITHUB_TOKEN: { from_secret: github_token }

- name: update-tap
  pull: always
  image: mcom/brewbuilder
  settings:
    formula: Formula/go-starter.rb
    hash_file: go-starter-darwin-amd64.tgz
    revision: ${DRONE_BUILD_NUMBER}
    tap: https://github.com/magento-mcom/homebrew-tap
    template: formula.template.rb
    url: https://github.com/magento-mcom/go-starter/releases/download/${DRONE_TAG}/go-starter-darwin-amd64.tgz
    version: ${DRONE_TAG}

---
kind: secret
name: docker_registry
get:
  path: secret/dx_magento_mom_droneci/registry/docker.io
  name: config

---
kind: secret
name: docker_username
get:
  path: secret/dx_magento_mom_droneci/registry/docker.io
  name: username

---
kind: secret
name: docker_password
get:
  path: secret/dx_magento_mom_droneci/registry/docker.io
  name: password

---
kind: secret
name: github_token
get:
  path: secret/dx_magento_mom_droneci/github
  name: token
